title: Jiaxi Yang (杨佳希)
logo: /assets/img/ruiping_3.jpg
description: M.S. Student in Beijing University of Posts and Telecommunications
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
